workflows:
  ios-workflow:
    name: iOS IPA Build
    environment:
      groups: []
    scripts:
      - name: Flutter setup
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS IPA
        script: |
          flutter build ipa --no-codesign --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - xjbravev378@gmail.com