workflows:
  ios-workflow:
    name: iOS IPA Build
    environment:
      groups: []
    scripts:
      - name: Build IPA
        script: |
          flutter build ipa --no-codesign --release
    artifacts:
      - build/ios/ipa/*.ipa