workflows:
  ios-workflow:
    name: iOS IPA Build
    environment:
      groups: []
    scripts:
      - name: Flutter setup
        script: |
          flutter clean
          flutter pub get
      - name: Generate iOS files
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa